import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LandingPage from './landingPage'
import Admin from './admin_dashboard/admin'
import ListRouter from './admin_dashboard/dummy'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <>
      <Head>
        <title>Anomaly Detection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{height:'100vh', display:'flex', alignItems:'center'}}>
        {/* <LandingPage/> */}
        <Admin/>
        {/* <ListRouter/> */}
      </main>
    </>
  )
}

/*
// map
import React from "react";
import dynamic from "next/dynamic";

export default function Home() {
  const MapWithNoSSR = dynamic(() => import("../pages/admin_dashboard/Map"), {
    ssr: false
  });

  return (
    <main>
      <div id="map">
        <MapWithNoSSR />
      </div>
    </main>
  );
}
*/